# Generated by Django 3.2 on 2023-01-27 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pushlished_date',
            new_name='published_date',
        ),
    ]
