# Generated by Django 3.2.17 on 2023-02-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='req_item_lev',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
