# Generated by Django 3.2.17 on 2023-02-17 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('raid_name', models.CharField(max_length=50)),
                ('req_item_lev', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('party_size', models.IntegerField()),
                ('party_state', models.IntegerField()),
                ('cur_raid_id', models.ForeignKey(db_column='raid_id', on_delete=django.db.models.deletion.CASCADE, related_name='raid', to='obj_create.raid')),
            ],
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_party_id', models.ForeignKey(db_column='party_id', on_delete=django.db.models.deletion.CASCADE, related_name='party', to='obj_create.party')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
